---
driver:
  name: docker
  hostname: maas.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_copy_filter:
    - .kitchen
    - .git
  require_chef: false
  formula: maas
  log_level: info
  state_top:
    base:
      "*":
        - linux
        - postgresql
        - maas
  pillars:
    top.sls:
      base:
        "*":
          - linux
          - postgresql
          - maas

  pillars-from-files:
    postgresql.sls: tests/pillar/postgresql.sls
    linux.sls: tests/pillar/linux.sls

  grains:
    noservices: False
    kitchen-test: True

  dependencies:
    - name: postgresql
      repo: git
      source: https://github.com/salt-formulas/salt-formula-postgresql
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux

platforms:
  - name: <%=ENV['PLATFORM'] ||  'ubuntu-18.04' %>
    driver_config:
      run_command: /sbin/init
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      platform: ubuntu
      provision_command:
        - apt-get clean && rm -rf /var/lib/apt/lists/* && apt-get update && apt-get install -y git language-pack-en
        - localedef -i en_US -f UTF-8 en_US.UTF-8

verifier:
  name: inspec
  sudo: true

suites:
  - name: maas_cluster
    provisioner:
      pillars-from-files:
        maas.sls: tests/pillar/maas_cluster.sls

  #- name: disk_layout
    #provisioner:
      #pillars-from-files:
        #maas.sls: tests/pillar/disk_layout.sls

  #- name: maas_mirror
    #provisioner:
      #pillars-from-files:
        #maas.sls: tests/pillar/maas_mirror.sls

  - name: maas_region
    provisioner:
      pillars-from-files:
        maas.sls: tests/pillar/maas_region.sls
    driver_config:
      forward:
        - 5240:5240

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
