language: python
services:
  - docker

jobs:
  include:
    - name: "Ubuntu Xenial"
      os: linux
      dist: xenial
      python: 3.6
      env:
        PLATFORM=ubuntu-16.04
    - name: "Ubuntu Bionic"
      os: linux
      dist: bionic
      python: 3.6
      env:
        PLATFORM=ubuntu-18.04

addons:
  apt:
    packages:
    - apt-transport-https

install:
  #- apt-get install -y python-yaml virtualenv git
  - pip install PyYAML
  - pip install virtualenv
  - |
    if [ ! -e Gemfile ]; then
       curl -s -o ./Gemfile 'https://raw.githubusercontent.com/salt-formulas/salt-formulas-scripts/master/Gemfile'
    fi
  - bundle install

before_script:
  - set -o pipefail
  - make test

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration
