language: python
services:
  - docker

jobs:
  include:
    - name: "Ubuntu Trusty"
      os: linux
      dist: trusty
      python: 2.7
    - name: "Ubuntu Xenial"
      os: linux
      dist: xenial
      python: 3
    - name: "Ubuntu Bionic"
      os: linux
      dist: bionic
      python: 3

addons:
  apt:
    packages:
    - apt-transport-https

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    if [ ! -e Gemfile ]; then
       curl -s -o ./Gemfile 'https://raw.githubusercontent.com/salt-formulas/salt-formulas-scripts/master/Gemfile'
    fi
  - bundle install

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration
