language: python
python:
- "2.7.13"
sudo: required
services:
  - docker

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

addons:
  apt:
    packages:
    - apt-transport-https

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    if [ ! -e Gemfile ]; then
       curl -s -o ./Gemfile 'https://raw.githubusercontent.com/salt-formulas/salt-formulas-scripts/master/Gemfile'
    fi
  - bundle install

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration
